spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.hosts}
      database: ${mongodb.database}
rarible:
  core:
    ethereum:
      url: ${node.hosts}
      web-socke-turl: ${node.webSocketHosts}
    apm:
      agent:
        enabled: true
        server: http://elk_apm-server:8200
        packages: org.rarible.ethereum.erc20.api
