spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.hosts}
      database: ${mongodb.database}
      username: ${mongodb.username}
      password: ${mongodb.password}
rarible:
  core:
    ethereum:
      url: ${node.hosts}
      web-socke-turl: ${node.webSocketHosts}
