apiVersion: v2
name: protocol
version: 0.1.0
dependencies:
- name: rarible-helm-chart
  alias: protocol-erc20-listener
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: protocol-erc20-api
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: protocol-gateway
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: protocol-order-api
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: protocol-order-listener
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: protocol-order-migration
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: protocol-unlockable-api
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: protocol-nft-api
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: protocol-nft-listener
  repository: file://../resources/helm/rarible
  version: 0.1.0