common:
  chain-id: 3
  exchange-contract-addresses:
    crypto-punks: "0x8Dcd3a0aea22925590Dbba0f13cCbA87b238c766"
logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG