spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.hosts}
      database: ${mongodb.database}
rarible:
  ethereum:
    httpUrl: ${node.hosts}
    websocketUrl: ${node.webSocketHosts}
blockchain:
  scanner:
    kafka:
      broker-replica-set: ${kafka.hosts}
