spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.hosts}
      database: ${mongodb.database}
      username: ${mongodb.username}
      password: ${mongodb.password}

protocol:
  nft:
    subscriber:
      broker-replica-set: ${kafka.hosts}
  order:
    subscriber:
      broker-replica-set: ${kafka.hosts}
  unlockable:
    subscriber:
      broker-replica-set: ${kafka.hosts}
