spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.hosts}
      database: ${mongodb.database}
      username: ${mongodb.username}
      password: ${mongodb.password}

parityUrls: ${node.hosts}
parityWebSocketUrls: ${node.webSocketHosts}

jms-brokerUrls: ${broker.jms.hosts}
